import type { Metadata } from "next";
import { Space_Grotesk, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import MaxWidthWrapper from "./components/ui/max-width-wrapper";
import Footer from "./components/ui/footer";

const grotesk = Space_Grotesk({
  variable: "--font-grotesk",
  subsets: ["latin"],
});

const jetbrains = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pranav Pokale | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grotesk.variable} ${jetbrains.variable} antialiased bg-zinc-50 font-sans dark:bg-black p-4`}
      >
        <MaxWidthWrapper>
          <div className="flex-1">{children}</div>

          <Footer />
        </MaxWidthWrapper>
      </body>
    </html>
  );
}
